"""Azure AI Foundry PowerShell script generator.

Instead of deploying directly from Druppie, we generate a PowerShell script
that the user runs manually. The script handles Azure login and agent creation.
"""

import json

import structlog

logger = structlog.get_logger()

# LLM profile -> Foundry model mapping
PROFILE_MODEL_MAP = {
    "standard": "gpt-4.1-mini",
    "cheap": "gpt-4.1-mini",
    "ollama": "gpt-4.1-mini",
}


def generate_powershell_deploy_script(agent_detail, endpoint: str) -> str:
    """Generate a PowerShell script that deploys an agent to Azure AI Foundry.

    The script will:
    1. Login to Azure (interactive)
    2. Create/update the agent via the Foundry REST API
    """
    model = PROFILE_MODEL_MAP.get(agent_detail.llm_profile, "gpt-4.1-mini")

    # Escape the system prompt for embedding in PowerShell
    system_prompt_escaped = agent_detail.system_prompt.replace("'", "''")

    # Build the agent body as a dict, then serialize for the script
    agent_body = {
        "model": model,
        "name": agent_detail.agent_id,
        "instructions": agent_detail.system_prompt,
        "temperature": agent_detail.temperature,
    }
    agent_body_json = json.dumps(agent_body, indent=2)
    # Escape for PowerShell here-string (backticks for $ signs)
    agent_body_ps = agent_body_json.replace("$", "`$")

    endpoint_placeholder = endpoint or "<YOUR_FOUNDRY_PROJECT_ENDPOINT>"

    script = f"""#Requires -Modules Az.Accounts

<#
.SYNOPSIS
    Deploy agent '{agent_detail.name}' to Azure AI Foundry.

.DESCRIPTION
    Generated by Druppie. This script authenticates to Azure interactively
    and creates/updates the agent in your Foundry project.

    Prerequisites:
      - PowerShell 7+
      - Az PowerShell module: Install-Module Az -Scope CurrentUser
      - An Azure AI Foundry project endpoint

.NOTES
    Agent ID : {agent_detail.agent_id}
    Model    : {model}
#>

param(
    [string]$Endpoint = "{endpoint_placeholder}"
)

# --- 1. Login to Azure ---
Write-Host "Logging in to Azure..." -ForegroundColor Cyan
Connect-AzAccount -ErrorAction Stop | Out-Null
Write-Host "Logged in successfully." -ForegroundColor Green

# --- 2. Get access token for Cognitive Services ---
Write-Host "Acquiring token for Azure AI services..." -ForegroundColor Cyan
$tokenResponse = Get-AzAccessToken -ResourceUrl "https://cognitiveservices.azure.com" -ErrorAction Stop
$token = $tokenResponse.Token

# --- 3. Deploy the agent ---
$agentBody = @'
{agent_body_json}
'@

$headers = @{{
    "Authorization" = "Bearer $token"
    "Content-Type"  = "application/json"
}}

$uri = "$Endpoint/assistants?api-version=2025-05-01-preview"

Write-Host "Deploying agent '{agent_detail.agent_id}' to $Endpoint ..." -ForegroundColor Cyan

try {{
    $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $agentBody -ErrorAction Stop
    Write-Host ""
    Write-Host "Agent deployed successfully!" -ForegroundColor Green
    Write-Host "  Agent ID : $($response.id)" -ForegroundColor White
    Write-Host "  Name     : $($response.name)" -ForegroundColor White
    Write-Host "  Model    : $($response.model)" -ForegroundColor White
}} catch {{
    Write-Host ""
    Write-Host "Deployment failed:" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    if ($_.ErrorDetails.Message) {{
        Write-Host $_.ErrorDetails.Message -ForegroundColor Yellow
    }}
    exit 1
}}
"""
    return script
