{{- if .Values.keycloak.realmImport.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "druppie.fullname" . }}-realm-export
  labels:
    {{- include "druppie.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-realm
data:
  druppie-realm.json: |-
{{ .Files.Get "files/realm-export.json" | fromYaml | merge (dict "attributes" (merge (dict "frontendUrl" (printf "https://%s" .Values.global.domain)) (.Files.Get "files/realm-export.json" | fromYaml).attributes)) | toJson | indent 4 }}
{{- end }}
