{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ci-harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ci-harbor
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_USERNAME
      remoteRef:
        key: ci/harbor
        property: username
    - secretKey: HARBOR_PASSWORD
      remoteRef:
        key: ci/harbor
        property: password
{{- end }}
