{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vaultAddress | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.externalSecrets.vaultRole | quote }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccount | quote }}
{{- end }}
