#!/usr/bin/env python3
"""Generate the Current Architecture Specification (CAS) (PBI 9744).

The CAS is an auto-generated, deterministic overview of all **accepted** ADRs.
It contains NO timestamps or other changing content, so that a freshness check
(comparing the committed file to freshly rendered content) is stable.

Reuses the date-safe YAML loader from ``validate_docs`` so unquoted dates in
frontmatter are not coerced into ``datetime.date`` objects.
"""

import argparse
import re
from pathlib import Path

from validate_docs import extract_frontmatter, load_frontmatter

# Files like 001-something.md (skips TEMPLATE.md, *.schema.json, README).
ADR_NAME = re.compile(r"^\d{3}-.*\.md$")

_HEADER = (
    "<!-- AUTO-GENERATED by scripts/generate_cas.py — do NOT edit by hand.\n"
    "     Regenerate after accepting or superseding an ADR: "
    "python scripts/generate_cas.py -->\n"
    "# Current Architecture Specification (CAS)\n"
    "\n"
    "Consolidated view of all **accepted** ADRs. "
    "Individual ADRs live in `docs/adrs/`.\n"
    "\n"
)


def _collect_accepted_adrs(adrs_dir):
    """Return a list of (id, title, filename) for accepted ADRs, sorted by id."""
    accepted = []
    if not adrs_dir.is_dir():
        return accepted

    for path in sorted(adrs_dir.iterdir()):
        if not path.is_file():
            continue
        if not ADR_NAME.match(path.name):
            continue
        raw = extract_frontmatter(path.read_text(encoding="utf-8"))
        if raw is None:
            continue
        try:
            data = load_frontmatter(raw)
        except Exception:
            continue
        if not isinstance(data, dict):
            continue
        if data.get("status") != "accepted":
            continue
        accepted.append(
            (str(data.get("id", "")), str(data.get("title", "")), path.name)
        )

    accepted.sort(key=lambda row: row[0])
    return accepted


def render_cas(root):
    """Return the deterministic CAS markdown for the repo at ``root``."""
    root = Path(root)
    accepted = _collect_accepted_adrs(root / "docs" / "adrs")

    parts = [_HEADER]

    if accepted:
        parts.append("| ADR | Title |\n")
        parts.append("|-----|-------|\n")
        for adr_id, title, filename in accepted:
            parts.append(f"| [{adr_id}]({filename}) | {title} |\n")
    else:
        parts.append("_No accepted ADRs yet._\n")

    text = "".join(parts)
    # Single trailing newline.
    return text.rstrip("\n") + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate docs/adrs/CAS.md from accepted ADRs."
    )
    default_root = Path(__file__).resolve().parent.parent
    parser.add_argument(
        "--root",
        type=Path,
        default=default_root,
        help="Repo root (default: script's parent.parent).",
    )
    args = parser.parse_args()
    root = args.root.resolve()

    out_path = root / "docs" / "adrs" / "CAS.md"
    out_path.write_text(render_cas(root), encoding="utf-8")
    print(f"Wrote {out_path.relative_to(root).as_posix()}")


if __name__ == "__main__":
    main()
