# @status active
# @superseded_by
# @adr 016-context-window-management.md

@adr docs/adrs/016-context-window-management.md
Feature: Auto-compression of agent conversation context
  # The "why" (problem, decision, alternatives) lives in the linked ADR (@adr).
  # This spec holds only the acceptance Scenarios for the implemented behavior.

  Scenario: Compression triggers when estimated tokens exceed threshold
    Given an agent with max_context_tokens 150000 and summarization_threshold 0.70
    When the estimated token count of the conversation exceeds 105000
    Then MessageCompactor.compress() is called before the next LLM turn
    And the conversation body is replaced with a summary message

  Scenario: Header is preserved during compression
    Given a conversation with leading system and initial-user messages (the header)
    When compression fires
    Then the header messages remain verbatim in the conversation
    And only the body (messages after the header) is summarized and replaced

  Scenario: Compression produces a single summary message
    Given a conversation body with many tool calls and responses
    When compression succeeds
    Then the body is replaced with a single user message starting with [CONVERSATION SUMMARY]
    And the summary is at most 300 words generated by the agent's own LLM

  Scenario: Agent is forced done after max compactions
    Given an agent with max_compactions set to 5
    When the agent has already been compressed 5 times
    Then the loop forces done() with an AUTO-DONE message
    And no further LLM turns are attempted

  Scenario: Agent is forced done on context overflow after compression
    Given a conversation that was just compressed
    When the estimated token count still exceeds max_context_tokens
    Then the loop forces done() with an AUTO-DONE: Context limit reached message

  Scenario: Per-agent YAML configuration controls compression thresholds
    Given a developer agent with compression.summarization_threshold 0.65
    And an architect agent with compression.max_compactions 5
    When each agent runs in a long session
    Then the developer triggers compression at 65% of max_context_tokens
    And the architect is force-done after 5 compactions

  Scenario: Fallback drops history when LLM summarization fails
    Given a conversation that triggers compression
    When the LLM call for summarization fails or no LLM is available
    Then the body is replaced with a placeholder message
    And the phase is recorded as summarized_fallback in CompactionEvent

  Scenario: Tool results are independently truncated
    Given a tool call that returns a very large result
    When the result exceeds the tool_result_max_chars limit (default 15000)
    Then the result is truncated with head and tail preserved
    And a truncation notice is inserted indicating how many chars were omitted

  Scenario: Compaction events are persisted for audit
    Given a compression that has occurred
    When the CompactionEvent is emitted
    Then it is persisted with phase, tokens_before, tokens_after, turns_compressed, and summary_text
    And it is queryable per agent run and per session
