"""Tests for the Document Formatter Service.

Covers Typst-based PDF compilation from native .typ source files.
Run these tests after `docker compose --profile dev up -d` (or locally
if typst is installed) to verify the document pipeline.
"""
from __future__ import annotations

import io
import re
import subprocess
from pathlib import Path
from unittest.mock import patch

import pypdf
import pytest

from druppie.domain import DocumentHouseStyle
from druppie.services.document_formatter_service import (
    DocumentFormatterError,
    DocumentFormatterService,
)


def _test_input(name: str) -> Path:
    """Return path to a test fixture .typ file."""
    return Path(__file__).parent.parent / "templates" / "documents" / "test-inputs" / f"{name}.typ"


class TestDocumentFormatterFunctional:
    """PDF compilation end-to-end with real Typst engine."""

    def test_service_finds_typst_binary(self):
        """Sanity check that typst binary and template dir resolve."""
        svc = DocumentFormatterService()
        assert svc.typst_bin is not None
        assert Path(svc.typst_bin).exists()

    def test_functioneel_ontwerp_compiles(self):
        """FO .typ → PDF with correct page count and structure."""
        svc = DocumentFormatterService()
        typ_path = _test_input("functional-design")

        pdf_bytes = svc.compile_typ(typ_path)

        assert len(pdf_bytes) > 1000

        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        assert len(reader.pages) >= 3  # Title + TOC + content pages

        full_text = ""
        for page in reader.pages:
            full_text += page.extract_text() or ""
        assert "Inleiding" in full_text
        assert "Inhoudsopgave" in full_text  # TOC generated by template
        assert "Functioneel" in full_text or "Functioneel Ontwerp" in full_text

    def test_technisch_ontwerp_compiles(self):
        """TO .typ with table-heavy content renders."""
        svc = DocumentFormatterService()
        typ_path = _test_input("technical-design")

        pdf_bytes = svc.compile_typ(typ_path)

        assert len(pdf_bytes) > 1000
        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        assert len(reader.pages) >= 3

        full_text = ""
        for page in reader.pages:
            full_text += page.extract_text() or ""
        assert "Architectuur" in full_text
        assert "Data Model" in full_text
        assert "Integratie" in full_text

    def test_draft_watermark_present(self):
        """DRAFT status produces a visible watermark."""
        svc = DocumentFormatterService()
        typ_path = _test_input("functional-design")

        pdf_bytes = svc.compile_typ(typ_path)

        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        first_page = reader.pages[0]
        text = first_page.extract_text() or ""
        assert "DRAFT" in text or "Niet-definitief" in text

    def test_final_no_watermark(self):
        """FINAL status omits the watermark."""
        svc = DocumentFormatterService()
        rel_template = svc.template_dir.relative_to(Path(svc.project_root)) / "rijnland.typ"

        tmp = Path("/app") / "tmp" / "test-final.typ"
        tmp.write_text(
            f'#import "/{rel_template}": rijnland_doc\n\n'
            f'#show: rijnland_doc.with(\n'
            f'  title: "Final Test",\n'
            f'  document_type: "functional_design",\n'
            f'  status: "FINAL",\n'
            f'  project_name: "Test",\n'
            f'  include_toc: false,\n'
            f'  include_watermark: true,\n'
            f'  section_breaks: false,\n'
            f')\n\n'
            f'= Test Section\n\nSome content.\n',
            encoding="utf-8",
        )

        pdf_bytes = svc.compile_typ(tmp)

        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        first_page = reader.pages[0]
        text = first_page.extract_text() or ""
        assert "DRAFT" not in text
        assert "Niet-definitief" not in text.upper()

    def test_invalid_template_path_raises(self):
        """Missing template should raise DocumentFormatterError early."""
        with pytest.raises(DocumentFormatterError):
            DocumentFormatterService(template_dir="/nonexistent/path")

    @pytest.mark.parametrize("doc_type", ["functional_design", "technical_design"])
    def test_all_document_types_compile(self, doc_type):
        """Ensure each supported document_type compiles without error."""
        svc = DocumentFormatterService()
        tmp = Path("/app") / "tmp" / f"test-{doc_type}.typ"
        rel_template = svc.template_dir.relative_to(Path(svc.project_root)) / "rijnland.typ"
        tmp.write_text(
            f'#import "/{rel_template}": rijnland_doc\n\n'
            f'#show: rijnland_doc.with(\n'
            f'  title: "Test Document",\n'
            f'  document_type: "{doc_type}",\n'
            f'  status: "DRAFT",\n'
            f'  project_name: "Test",\n'
            f'  include_toc: false,\n'
            f'  include_watermark: false,\n'
            f'  section_breaks: false,\n'
            f')\n\n'
            f'= Section\n\nSome content.\n',
            encoding="utf-8",
        )
        pdf_bytes = svc.compile_typ(tmp)
        assert len(pdf_bytes) > 100

    def test_hhsk_functioneel_ontwerp_compiles(self):
        """The HHSK house-style fixture compiles to a real PDF."""
        svc = DocumentFormatterService()
        typ_path = _test_input("hhsk-functional-design")

        pdf_bytes = svc.compile_typ(typ_path)

        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        assert len(reader.pages) >= 1

    @pytest.mark.parametrize("style", list(DocumentHouseStyle))
    def test_every_house_style_template_compiles(self, style):
        """Each DocumentHouseStyle maps to a template that actually compiles.

        Guards the enum -> template mapping: if a style's template_path or
        template_function is wrong, the import fails and this test catches it.
        Both templates take an identical parameter list, so the same body
        works for every style.
        """
        svc = DocumentFormatterService()
        tmp = Path("/app") / "tmp" / f"test-style-{style.value}.typ"
        tmp.write_text(
            f'{style.import_line}\n\n'
            f'#show: {style.template_function}.with(\n'
            f'  title: "House Style Test",\n'
            f'  document_type: "functional_design",\n'
            f'  status: "DRAFT",\n'
            f'  project_name: "Test",\n'
            f'  include_toc: false,\n'
            f'  include_watermark: false,\n'
            f'  section_breaks: false,\n'
            f')\n\n'
            f'= Section\n\nSome content.\n',
            encoding="utf-8",
        )

        pdf_bytes = svc.compile_typ(tmp)
        assert len(pdf_bytes) > 100

    @pytest.mark.parametrize(
        "style,stripe_rgb",
        [
            # Colours are the ones each template defines for odd body rows.
            (DocumentHouseStyle.RIJNLAND, (0xE9, 0xEF, 0xFA)),  # rijnland-blauw-10
            (DocumentHouseStyle.HHSK, (0xD2, 0xEE, 0xF0)),      # lichtblauw-40
        ],
    )
    def test_table_zebra_striping_renders(self, style, stripe_rgb):
        """Odd table rows are actually filled with the stripe colour.

        Regression test: both templates previously risked using
        `show table.cell.where(y: <predicate>)`, which silently matches
        nothing because `.where()` compares literal field values rather than
        calling a predicate. Striping must come from table's `fill` callback.
        We assert on the PDF content stream so a non-rendering rule fails.
        """
        svc = DocumentFormatterService()
        tmp = Path("/app") / "tmp" / f"test-zebra-{style.value}.typ"
        tmp.write_text(
            f'{style.import_line}\n\n'
            f'#show: {style.template_function}.with(\n'
            f'  title: "Zebra",\n'
            f'  document_type: "technical_design",\n'
            f'  status: "FINAL",\n'
            f'  project_name: "Test",\n'
            f'  include_toc: false,\n'
            f'  include_watermark: false,\n'
            f'  section_breaks: false,\n'
            f')\n\n'
            f'= Table\n\n'
            f'#table(columns: 2, [H1],[H2], [a1],[a2], [b1],[b2], [c1],[c2])\n',
            encoding="utf-8",
        )

        pdf_bytes = svc.compile_typ(tmp)

        expected = " ".join(f"{channel / 255:.4f}".rstrip("0") for channel in stripe_rgb)
        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        fills: set[str] = set()
        for page in reader.pages:
            stream = page["/Contents"].get_data().decode("latin-1")
            fills.update(re.findall(r"([0-9.]+ [0-9.]+ [0-9.]+) scn", stream))

        # Compare rounded triples so float formatting differences don't matter.
        found = {
            tuple(round(float(component), 3) for component in fill.split())
            for fill in fills
        }
        target = tuple(round(channel / 255, 3) for channel in stripe_rgb)
        assert target in found, (
            f"stripe colour {expected} not present in rendered table; "
            f"found fills: {sorted(found)}"
        )

    def test_verify_typ_reports_syntax_ok(self):
        """verify_typ returns True for a clean .typ file."""
        svc = DocumentFormatterService()
        tmp = Path("/app") / "tmp" / "test-valid.typ"
        rel_template = svc.template_dir.relative_to(Path(svc.project_root)) / "rijnland.typ"
        tmp.write_text(
            f'#import "/{rel_template}": rijnland_doc\n\n'
            f'#show: rijnland_doc.with(title: "OK")\n= Test\n',
            encoding="utf-8",
        )
        is_valid, error = svc.verify_typ(tmp)
        assert is_valid is True
        assert error is None

    def test_verify_typ_reports_syntax_error(self):
        """verify_typ returns False for a broken .typ file."""
        svc = DocumentFormatterService()
        tmp = Path("/app") / "tmp" / "test-invalid.typ"
        tmp.write_text(
            "#broken syntax { UNSPECIFIED\n",
            encoding="utf-8",
        )
        is_valid, error = svc.verify_typ(tmp)
        assert is_valid is False
        assert error is not None

    def test_compile_typ_missing_file(self):
        """compile_typ raises DocumentFormatterError for missing source file."""
        svc = DocumentFormatterService()
        with pytest.raises(DocumentFormatterError, match="not found"):
            svc.compile_typ("/nonexistent/path/test.typ")


class TestDocumentFormatterMocked:
    """Unit tests with mocked subprocess for fast, no-Docker execution.

    These cover the failure branches that integration tests cannot hit
    without actually breaking a real Typst binary.
    """

    def test_typst_binary_not_found_raises(self):
        """Initialising service without typst in PATH raises immediately."""
        with patch(
            "druppie.services.document_formatter_service.shutil.which",
            return_value=None,
        ):
            with pytest.raises(DocumentFormatterError, match="Typst binary not found"):
                DocumentFormatterService()

    def test_compile_typ_subprocess_timeout(self):
        """Typst timeout produces a clear DocumentFormatterError."""
        svc = DocumentFormatterService()
        dummy = Path("/app") / "tmp" / "test-timeout.typ"
        dummy.write_text(
            '#import "/druppie/templates/documents/rijnland.typ": rijnland_doc\n'
            '#show: rijnland_doc.with()\n= A\n',
            encoding="utf-8",
        )
        with patch(
            "druppie.services.document_formatter_service.subprocess.run",
            side_effect=subprocess.TimeoutExpired(cmd="typst", timeout=60),
        ):
            with pytest.raises(DocumentFormatterError, match="timed out"):
                svc.compile_typ(dummy)

    def test_compile_typ_subprocess_failure(self):
        """Typst returning a non-zero exit code surfaces stderr."""
        svc = DocumentFormatterService()
        dummy = Path("/app") / "tmp" / "test-fail.typ"
        dummy.write_text(
            '#import "/druppie/templates/documents/rijnland.typ": rijnland_doc\n'
            '#show: rijnland_doc.with()\n= B\n',
            encoding="utf-8",
        )
        err = subprocess.CalledProcessError(
            returncode=1,
            cmd="typst",
            stderr="error: file not found\n",
        )
        with patch(
            "druppie.services.document_formatter_service.subprocess.run",
            side_effect=err,
        ):
            with pytest.raises(DocumentFormatterError, match="Typst compilation failed"):
                svc.compile_typ(dummy)

    def test_compile_typ_missing_output_pdf(self):
        """If Typst exits 0 but no PDF is created, raise a sensible error."""
        svc = DocumentFormatterService()
        dummy = Path("/app") / "tmp" / "test-no-pdf.typ"
        dummy.write_text(
            '#import "/druppie/templates/documents/rijnland.typ": rijnland_doc\n'
            '#show: rijnland_doc.with()\n= C\n',
            encoding="utf-8",
        )
        fake_path = Path("/app/tmp/nonexistent-output.pdf")
        with patch(
            "druppie.services.document_formatter_service.subprocess.run",
            return_value=subprocess.CompletedProcess(args=[], returncode=0),
        ):
            with pytest.raises(DocumentFormatterError, match="PDF output was not created"):
                svc.compile_typ(dummy, output_pdf_path=fake_path)

    def test_verify_typ_subprocess_timeout(self):
        """verify_typ returns gracefully on timeout."""
        svc = DocumentFormatterService()
        dummy = Path("/app") / "tmp" / "test-verify-timeout.typ"
        dummy.write_text(
            '#import "/druppie/templates/documents/rijnland.typ": rijnland_doc\n'
            '#show: rijnland_doc.with()\n= D\n',
            encoding="utf-8",
        )
        with patch(
            "druppie.services.document_formatter_service.subprocess.run",
            side_effect=subprocess.TimeoutExpired(cmd="typst", timeout=60),
        ):
            is_valid, error = svc.verify_typ(dummy)
            assert is_valid is False
            assert "timed out" in (error or "").lower()
