"""Tests for the Document Formatter Service.

Covers Typst-based PDF generation from markdown + metadata.
Run these tests after `docker compose --profile dev up -d` (or locally
if typst is installed) to verify the document pipeline.
"""
from __future__ import annotations

import io
import json
from pathlib import Path

import pypdf
import pytest

from druppie.services.document_formatter_service import (
    DocumentFormatterError,
    DocumentFormatterService,
)


def _load_test_input(name: str) -> tuple[str, dict]:
    """Load markdown + metadata from test fixtures directory.
    Expects files named `{name}.md` and `{name}-metadata.json`."""
    base = Path(__file__).parent.parent / "templates" / "documents" / "test-inputs"
    md = (base / f"{name}.md").read_text(encoding="utf-8")
    meta = json.loads((base / f"{name}-metadata.json").read_text(encoding="utf-8"))
    return md, meta


class TestDocumentFormatterFunctional:
    """PDF generation end-to-end with real Typst engine."""

    def test_service_finds_template(self):
        """Sanity check that the default template path resolves."""
        svc = DocumentFormatterService()
        assert svc.base_template.exists()
        assert svc.base_template.name == "base.typ"

    def test_functioneel_ontwerp_renders(self):
        """FO markdown → PDF with correct page count and structure."""
        svc = DocumentFormatterService()
        content, meta = _load_test_input("functional-design")

        pdf_bytes = svc.generate_pdf(content=content, metadata=meta)

        # Basic sanity: non-empty PDF
        assert len(pdf_bytes) > 1000

        # Structural check with pypdf
        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        assert len(reader.pages) >= 3  # Title + TOC + content pages

        # Title should appear somewhere in the document
        full_text = ""
        for page in reader.pages:
            full_text += page.extract_text() or ""
        assert "Permit Metadata Search" in full_text
        assert "Inhoudsopgave" in full_text  # TOC generated by template

    def test_technisch_ontwerp_renders(self):
        """TO markdown → PDF with table-heavy content."""
        svc = DocumentFormatterService()
        content, meta = _load_test_input("technical-design")

        pdf_bytes = svc.generate_pdf(content=content, metadata=meta)

        assert len(pdf_bytes) > 1000
        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        assert len(reader.pages) >= 3

        full_text = ""
        for page in reader.pages:
            full_text += page.extract_text() or ""
        # pypdf text extraction inserts spaces in styled headings; normalize before checking
        normalized = full_text.replace(" ", "")
        assert "TechnicalDesign" in normalized
        assert "NORA" in full_text  # Architecture reference from real TO

    def test_draft_watermark_present(self):
        """DRAFT status produces a visible watermark."""
        svc = DocumentFormatterService()
        content, meta = _load_test_input("functional-design")
        meta["status"] = "DRAFT"

        pdf_bytes = svc.generate_pdf(content=content, metadata=meta)

        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        first_page = reader.pages[0]
        text = first_page.extract_text() or ""
        # Watermark is in page background; badge "Niet-definitief" appears on title page
        assert "DRAFT" in text or "Niet-definitief" in text

    def test_final_no_watermark(self):
        """FINAL status omits the watermark."""
        svc = DocumentFormatterService()
        content, meta = _load_test_input("functional-design")
        meta["status"] = "FINAL"
        meta["include_watermark"] = False

        pdf_bytes = svc.generate_pdf(content=content, metadata=meta)

        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        first_page = reader.pages[0]
        text = first_page.extract_text() or ""
        assert "DRAFT" not in text
        assert "Niet-definitief" not in text.upper()

    def test_invalid_template_path_raises(self):
        """Missing template should raise FileNotFoundError early."""
        with pytest.raises(FileNotFoundError):
            DocumentFormatterService(template_dir="/nonexistent/path")

    @pytest.mark.parametrize("doc_type", ["functional_design", "technical_design"])
    def test_all_document_types(self, doc_type):
        """Ensure each supported document_type compiles without error."""
        svc = DocumentFormatterService()
        content = "# Test\n\nSome content."
        meta = {
            "document_type": doc_type,
            "title": "Test Document",
            "status": "DRAFT",
            "project_name": "Test Project",
            "include_toc": False,
            "include_watermark": False,
            "section_breaks": False,
        }
        pdf_bytes = svc.generate_pdf(content=content, metadata=meta)
        assert len(pdf_bytes) > 100
